services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_app
    restart: unless-stopped
    networks:
      - web_proxy

networks:
  web_proxy:
    external: true
